'use server';
import { revalidatePath, updateTag } from 'next/cache';
import { isAdminAuthError, requireAdmin } from '@/lib/auth/requireAdmin';
import { MEDIA_PAGE_CACHE_TAG, MediaPageDataError, persistMediaPageDraft, promoteMediaPageDraft } from '@/lib/mediaPageRepository';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function validate(input){const e={}; if(!UUID.test(input?.id||''))e.id='A valid Media page version is required.';if(!input?.updatedAt||Number.isNaN(Date.parse(input.updatedAt)))e.updatedAt='Refresh before saving.';if(input?.sectionKey!=='media-page')e.sectionKey='Only Media Center content is accepted.';if(!input?.content?.header?.mediaId)e.headerMedia='Select a page header image.';const articles=input?.content?.articles,videos=input?.content?.videos;if(!Array.isArray(articles)||articles.length<1||articles.length>100)e.articles='Add between 1 and 100 articles.';if(!Array.isArray(videos)||videos.length>30)e.videos='Add at most 30 videos.';const slugs=new Set();for(const [i,a] of(articles||[]).entries()){if(!UUID.test(a.postId||''))e[`articles.${i}.postId`]='Stable post ID required.';if(!a.title?.trim())e[`articles.${i}.title`]='Title required.';if(!a.slug?.trim()||a.slug.includes('/')||a.slug.length>400)e[`articles.${i}.slug`]='Use a non-empty URL segment without slashes.';if(slugs.has(a.slug))e[`articles.${i}.slug`]='Slugs must be unique.';slugs.add(a.slug);if(!['Latest News','Blogs & Articles'].includes(a.category))e[`articles.${i}.category`]='Choose a supported category.';if(!a.content?.trim())e[`articles.${i}.content`]='Article body required.';if(!a.coverMediaId||!a.coverAlt?.trim())e[`articles.${i}.cover`]='Cover image and alt text required.';}for(const [i,v] of(videos||[]).entries()){if(!UUID.test(v.videoId||''))e[`videos.${i}.videoId`]='Stable video ID required.';if(!v.title?.trim()||!v.embedUrl?.startsWith('https://'))e[`videos.${i}`]='Video title and HTTPS embed URL required.';if(!v.thumbnailMediaId||!v.thumbnailAlt?.trim())e[`videos.${i}.thumbnail`]='Thumbnail and alt text required.';}return e;}
function failure(error){if(isAdminAuthError(error))return{ok:false,status:error.status,code:error.code,error:error.message};if(error instanceof MediaPageDataError)return{ok:false,status:error.status,code:error.code,error:error.status>=500?'The Media Center request could not be completed.':error.message};console.error('Unexpected Media Center action failure:',error);return{ok:false,status:500,code:'MEDIA_PAGE_ACTION_FAILED',error:'The Media Center request could not be completed.'};}
export async function saveMediaPageDraft(input){try{await requireAdmin();const fieldErrors=validate(input);if(Object.keys(fieldErrors).length)return{ok:false,status:422,code:'VALIDATION_ERROR',error:'Review the Media Center fields.',fieldErrors};return await persistMediaPageDraft(input);}catch(error){return failure(error);}}
export async function publishMediaPageDraft(input){try{await requireAdmin();if(!UUID.test(input?.id||'')||!input?.expectedUpdatedAt)return{ok:false,status:422,code:'VALIDATION_ERROR',error:'A current saved Media draft is required.'};const result=await promoteMediaPageDraft(input);if(result.ok){updateTag(MEDIA_PAGE_CACHE_TAG);updateTag('home:media-highlights:published');revalidatePath('/media-center');revalidatePath('/media-center/[slug]','page');revalidatePath('/');}return result;}catch(error){return failure(error);}}
