// Curated, tree-shaken FontAwesome SVG map for the public website
// Strictly includes only verified public & published CMS icons.
import {
  faAngleDown,
  faArrowLeft,
  faArrowRight,
  faArrowRightLong,
  faArrowUp,
  faArrowUpRightFromSquare,
  faArrowsLeftRight,
  faAward,
  faBolt,
  faBriefcase,
  faBuilding,
  faCalendarDays,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlay,
  faCircleQuestion,
  faCity,
  faCloudArrowUp,
  faCouch,
  faCubes,
  faElevator,
  faEnvelope,
  faEnvelopeOpenText,
  faExpand,
  faEye,
  faEyeSlash,
  faGaugeHigh,
  faGlobe,
  faHandshake,
  faLayerGroup,
  faLeaf,
  faLocationDot,
  faLock,
  faPaperPlane,
  faPause,
  faPhone,
  faPlay,
  faQuoteLeft,
  faRotateRight,
  faRulerCombined,
  faShieldHalved,
  faSpinner,
  faSquareCheck,
  faSquareParking,
  faTag,
  faUpDown,
  faUserCheck,
  faUsersGear,
  faVolumeHigh,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

import {
  faFacebook,
  faFacebookF,
  faInstagram,
  faLinkedin,
  faLinkedinIn,
  faTwitter,
  faWhatsapp,
  faXTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';

import {
  faCalendar as farCalendar,
  faCalendarDays as farCalendarDays,
  faComments as farComments,
  faImage as farImage,
  faUser as farUser,
} from '@fortawesome/free-regular-svg-icons';

export const FALLBACK_ICON = faCircleQuestion;

export const SOLID_ICONS = {
  "angle-down": faAngleDown,
  "fa-angle-down": faAngleDown,
  "arrow-left": faArrowLeft,
  "fa-arrow-left": faArrowLeft,
  "arrow-right": faArrowRight,
  "fa-arrow-right": faArrowRight,
  "arrow-right-long": faArrowRightLong,
  "fa-arrow-right-long": faArrowRightLong,
  "arrow-up": faArrowUp,
  "fa-arrow-up": faArrowUp,
  "arrow-up-right-from-square": faArrowUpRightFromSquare,
  "fa-arrow-up-right-from-square": faArrowUpRightFromSquare,
  "arrows-left-right": faArrowsLeftRight,
  "fa-arrows-left-right": faArrowsLeftRight,
  "award": faAward,
  "fa-award": faAward,
  "bolt": faBolt,
  "fa-bolt": faBolt,
  "briefcase": faBriefcase,
  "fa-briefcase": faBriefcase,
  "building": faBuilding,
  "fa-building": faBuilding,
  "calendar-days": faCalendarDays,
  "fa-calendar-days": faCalendarDays,
  "chart-line": faChartLine,
  "fa-chart-line": faChartLine,
  "check": faCheck,
  "fa-check": faCheck,
  "chevron-down": faChevronDown,
  "fa-chevron-down": faChevronDown,
  "chevron-left": faChevronLeft,
  "fa-chevron-left": faChevronLeft,
  "chevron-right": faChevronRight,
  "fa-chevron-right": faChevronRight,
  "circle-check": faCircleCheck,
  "fa-circle-check": faCircleCheck,
  "circle-exclamation": faCircleExclamation,
  "fa-circle-exclamation": faCircleExclamation,
  "circle-info": faCircleInfo,
  "fa-circle-info": faCircleInfo,
  "circle-play": faCirclePlay,
  "fa-circle-play": faCirclePlay,
  "circle-question": faCircleQuestion,
  "fa-circle-question": faCircleQuestion,
  "city": faCity,
  "fa-city": faCity,
  "cloud-arrow-up": faCloudArrowUp,
  "fa-cloud-arrow-up": faCloudArrowUp,
  "couch": faCouch,
  "fa-couch": faCouch,
  "cubes": faCubes,
  "fa-cubes": faCubes,
  "elevator": faElevator,
  "fa-elevator": faElevator,
  "envelope": faEnvelope,
  "fa-envelope": faEnvelope,
  "envelope-open-text": faEnvelopeOpenText,
  "fa-envelope-open-text": faEnvelopeOpenText,
  "expand": faExpand,
  "fa-expand": faExpand,
  "eye": faEye,
  "fa-eye": faEye,
  "eye-slash": faEyeSlash,
  "fa-eye-slash": faEyeSlash,
  "gauge-high": faGaugeHigh,
  "fa-gauge-high": faGaugeHigh,
  "globe": faGlobe,
  "fa-globe": faGlobe,
  "handshake": faHandshake,
  "fa-handshake": faHandshake,
  "layer-group": faLayerGroup,
  "fa-layer-group": faLayerGroup,
  "leaf": faLeaf,
  "fa-leaf": faLeaf,
  "location-dot": faLocationDot,
  "fa-location-dot": faLocationDot,
  "lock": faLock,
  "fa-lock": faLock,
  "paper-plane": faPaperPlane,
  "fa-paper-plane": faPaperPlane,
  "pause": faPause,
  "fa-pause": faPause,
  "phone": faPhone,
  "fa-phone": faPhone,
  "play": faPlay,
  "fa-play": faPlay,
  "quote-left": faQuoteLeft,
  "fa-quote-left": faQuoteLeft,
  "rotate-right": faRotateRight,
  "fa-rotate-right": faRotateRight,
  "ruler-combined": faRulerCombined,
  "fa-ruler-combined": faRulerCombined,
  "shield-halved": faShieldHalved,
  "fa-shield-halved": faShieldHalved,
  "spinner": faSpinner,
  "fa-spinner": faSpinner,
  "square-check": faSquareCheck,
  "fa-square-check": faSquareCheck,
  "square-parking": faSquareParking,
  "fa-square-parking": faSquareParking,
  "tag": faTag,
  "fa-tag": faTag,
  "up-down": faUpDown,
  "fa-up-down": faUpDown,
  "user-check": faUserCheck,
  "fa-user-check": faUserCheck,
  "users-gear": faUsersGear,
  "fa-users-gear": faUsersGear,
  "volume-high": faVolumeHigh,
  "fa-volume-high": faVolumeHigh,
  "xmark": faXmark,
  "fa-xmark": faXmark,
};

export const BRAND_ICONS = {
  "facebook": faFacebook,
  "fa-facebook": faFacebook,
  "facebook-f": faFacebookF,
  "fa-facebook-f": faFacebookF,
  "instagram": faInstagram,
  "fa-instagram": faInstagram,
  "linkedin": faLinkedin,
  "fa-linkedin": faLinkedin,
  "linkedin-in": faLinkedinIn,
  "fa-linkedin-in": faLinkedinIn,
  "twitter": faTwitter,
  "fa-twitter": faTwitter,
  "whatsapp": faWhatsapp,
  "fa-whatsapp": faWhatsapp,
  "x-twitter": faXTwitter,
  "fa-x-twitter": faXTwitter,
  "youtube": faYoutube,
  "fa-youtube": faYoutube,
};

export const REGULAR_ICONS = {
  "calendar": farCalendar,
  "fa-calendar": farCalendar,
  "calendar-days": farCalendarDays,
  "fa-calendar-days": farCalendarDays,
  "comments": farComments,
  "fa-comments": farComments,
  "image": farImage,
  "fa-image": farImage,
  "user": farUser,
  "fa-user": farUser,
};
