'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import ConcernDetailClient from '@/components/ConcernDetailClient';
import MediaLibrary from './MediaLibrary';
import { publishConcernsPageDraft, saveConcernsPageDraft } from '@/lib/concernsPageActions';

const INPUT = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-medium text-slate-800 outline-none focus:border-[#C5A880] focus:ring-2 focus:ring-[#C5A880]/20';
const LABEL = 'mb-1 block text-[11px] font-bold text-slate-700';
const TABS = ['Shared Content', 'Concerns', 'Preview', 'Advanced'];
const SHARED_FIELDS = [['aboutBreadcrumb','About breadcrumb'],['concernsBreadcrumb','Concerns breadcrumb'],['profileTag','Profile tag'],['overviewHeading','Overview heading'],['servicesTag','Services tag'],['servicesHeading','Services heading'],['portfolioTag','Portfolio tag'],['portfolioHeading','Portfolio heading'],['notFoundTitle','Not-found title'],['notFoundBody','Not-found description'],['returnLabel','Return button']];
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function stripMedia(content) { return { ...content, header: Object.fromEntries(Object.entries(content.header || {}).filter(([key]) => key !== 'media')), concerns: (content.concerns || []).map((item) => ({ ...Object.fromEntries(Object.entries(item).filter(([key]) => key !== 'coverMedia')), relatedProjects: (item.relatedProjects || []).map((project) => Object.fromEntries(Object.entries(project).filter(([key]) => !['coverMedia', 'coverMediaId', 'id', 'slug', 'name'].includes(key)))) })) }; }
function payload(page) { return { id: page.id, pageId: page.pageId, sectionKey: 'concerns-page', isVisible: page.isVisible, content: stripMedia(page.content), updatedAt: page.updatedAt }; }
function comparable(page) { return JSON.stringify(payload(page)); }
function orders(items) { return items.map((item, index) => ({ ...item, sortOrder: (index + 1) * 10 })); }
function move(items, index, direction) { const destination = index + direction; if (destination < 0 || destination >= items.length) return items; const next = [...items]; [next[index], next[destination]] = [next[destination], next[index]]; return orders(next); }
function mappedAsset(asset) { return { id: asset.id, secureUrl: asset.secure_url || asset.secureUrl || asset.url, displayName: asset.display_name || asset.displayName || asset.filename, altText: asset.alt_text || asset.altText || '', format: asset.format, width: asset.width, height: asset.height }; }
function Field({ label, value, onChange, multiline = false }) { const Control = multiline ? 'textarea' : 'input'; return <label><span className={LABEL}>{label}</span><Control rows={multiline ? 4 : undefined} value={value ?? ''} onChange={(event) => onChange(event.target.value)} className={INPUT} /></label>; }

function ConcernForm({ concern, availableProjects, onChange, onChooseCover }) {
  const set = (field, value) => onChange({ ...concern, [field]: value });
  const updateService = (index, patch) => set('services', concern.services.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  const linked = new Set(concern.relatedProjects.map((item) => item.projectId));
  const toggleProject = (project) => set('relatedProjects', linked.has(project.id) ? concern.relatedProjects.filter((item) => item.projectId !== project.id) : [...concern.relatedProjects, { projectId: project.id, badgeText: '', locationText: '', type: '' }]);
  return <div className="space-y-6">
    <div className="grid gap-3 md:grid-cols-3"><Field label="Concern name" value={concern.name} onChange={(value) => set('name', value)} /><Field label="URL slug" value={concern.slug} onChange={(value) => set('slug', value)} /><Field label="Subtitle" value={concern.subtitle} onChange={(value) => set('subtitle', value)} /></div>
    <Field label="Corporate overview" value={concern.overview} onChange={(value) => set('overview', value)} multiline />
    <div className="rounded-xl border p-4"><h3 className="font-serif text-sm font-bold text-[#0B1B3D]">Overview image</h3><div className="mt-3 flex flex-col gap-4 sm:flex-row">{concern.coverMedia?.secureUrl && <img src={concern.coverMedia.secureUrl} alt="" className="h-32 w-48 rounded-lg object-cover" />}<div className="flex-1"><Field label="Accessible image description" value={concern.coverAlt} onChange={(value) => set('coverAlt', value)} /><button type="button" onClick={onChooseCover} className="mt-3 rounded-lg bg-[#0B1B3D] px-3 py-2 text-xs font-bold text-white">Choose image</button></div></div></div>
    <div><div className="mb-3 flex items-center justify-between"><h3 className="font-serif text-sm font-bold">Key features</h3><button type="button" onClick={() => set('features', [...concern.features, 'New feature'])} className="rounded-lg border px-3 py-1.5 text-xs font-bold">+ Feature</button></div><div className="space-y-2">{concern.features.map((feature, index) => <div key={index} className="flex gap-2"><input value={feature} onChange={(event) => set('features', concern.features.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} className={INPUT} /><button type="button" onClick={() => confirm('Remove this feature?') && set('features', concern.features.filter((_, itemIndex) => itemIndex !== index))} className="rounded-lg border border-red-200 px-3 text-xs font-bold text-red-600">Remove</button></div>)}</div></div>
    <div><div className="mb-3 flex items-center justify-between"><h3 className="font-serif text-sm font-bold">Services and operations</h3><button type="button" onClick={() => set('services', [...concern.services, { icon: 'fa-building', title: 'New Service', description: 'Describe this capability.' }])} className="rounded-lg border px-3 py-1.5 text-xs font-bold">+ Service</button></div><div className="space-y-3">{concern.services.map((service, index) => <div key={index} className="grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-3"><Field label="Font Awesome icon" value={service.icon} onChange={(value) => updateService(index, { icon: value })} /><Field label="Service title" value={service.title} onChange={(value) => updateService(index, { title: value })} /><Field label="Description" value={service.description} onChange={(value) => updateService(index, { description: value })} multiline /><button type="button" onClick={() => confirm('Remove this service?') && set('services', concern.services.filter((_, itemIndex) => itemIndex !== index))} className="w-fit text-xs font-bold text-red-600">Remove service</button></div>)}</div></div>
    <div><h3 className="mb-1 font-serif text-sm font-bold">Related published projects</h3><p className="mb-3 text-[10px] text-slate-500">Project name, cover, badge, location and type are resolved from the canonical Projects catalogue.</p><div className="grid gap-2 md:grid-cols-2">{availableProjects.map((project) => <label key={project.id} className="flex items-center gap-2 rounded-lg border p-2 text-xs font-semibold"><input type="checkbox" checked={linked.has(project.id)} onChange={() => toggleProject(project)} /> {project.name}</label>)}</div></div>
    <label className="block rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-900"><input type="checkbox" checked={concern.isVisible !== false} onChange={(event) => set('isVisible', event.target.checked)} /> Publish this concern detail page and navigation entry</label>
  </div>;
}

export default function ConcernsPageEditor({ initialConcernsPage, initialSlug = '' }) {
  const router = useRouter();
  const initial = useMemo(() => clone(initialConcernsPage), [initialConcernsPage]);
  const [page, setPage] = useState(initial);
  const [baseline, setBaseline] = useState(comparable(initial));
  const [tab, setTab] = useState('Concerns');
  const [selectedIndex, setSelectedIndex] = useState(() => Math.max(0, initial.content.concerns.findIndex((item) => item.slug === initialSlug)));
  const [busy, setBusy] = useState('');
  const [message, setMessage] = useState('');
  const [tone, setTone] = useState('neutral');
  const [picker, setPicker] = useState(null);
  const [advanced, setAdvanced] = useState(() => JSON.stringify(payload(initial), null, 2));
  const dirty = comparable(page) !== baseline;
  const update = (patch) => { setPage((current) => ({ ...current, ...patch })); setMessage(''); };
  const setConcerns = (concerns) => update({ content: { ...page.content, concerns } });
  const updateConcern = (index, concern) => setConcerns(page.content.concerns.map((item, itemIndex) => itemIndex === index ? concern : item));
  const updateShared = (field, value) => update({ content: { ...page.content, labels: { ...page.content.labels, [field]: value } } });
  const chooseMedia = (asset) => { const item = page.content.concerns[picker.index]; updateConcern(picker.index, { ...item, coverMediaId: asset.id, coverMedia: mappedAsset(asset), coverAlt: item.coverAlt || asset.alt_text || item.name }); setPicker(null); };
  const addConcern = () => { const source = clone(page.content.concerns[0]); const concern = { ...source, concernId: crypto.randomUUID(), slug: `new-concern-${Date.now()}`, name: 'New Sister Concern', subtitle: 'New subsidiary profile', overview: 'Describe the concern and its operating scope.', relatedProjects: [], isVisible: false, sortOrder: (page.content.concerns.length + 1) * 10 }; setConcerns([...page.content.concerns, concern]); setSelectedIndex(page.content.concerns.length); };
  const save = async () => { setBusy('save'); setMessage(''); try { const result = await saveConcernsPageDraft(payload(page)); if (!result?.ok) { setTone('error'); setMessage(result?.error || 'Draft save failed.'); return; } const saved = { ...clone(result.data), history: page.history, availableProjects: page.availableProjects }; setPage(saved); setBaseline(comparable(saved)); setTone('success'); setMessage('Concerns draft saved. Public pages remain unchanged.'); } finally { setBusy(''); } };
  const publish = async () => { setBusy('publish'); setMessage(''); try { const result = await publishConcernsPageDraft({ id: page.id, expectedUpdatedAt: page.updatedAt }); if (!result?.ok) { setTone('error'); setMessage(result?.error || 'Publish failed.'); return; } const published = { ...clone(result.data), history: page.history, availableProjects: page.availableProjects }; setPage(published); setBaseline(comparable(published)); setTone('success'); setMessage('Concerns catalogue published and public routes revalidated.'); router.refresh(); } finally { setBusy(''); } };
  const applyAdvanced = () => { try { const parsed = JSON.parse(advanced); setPage((current) => ({ ...current, ...parsed, id: current.id, pageId: current.pageId, updatedAt: current.updatedAt, history: current.history, availableProjects: current.availableProjects })); setTone('success'); setMessage('Structured content applied locally.'); } catch (error) { setTone('error'); setMessage(`Invalid structured content: ${error.message}`); } };
  const selected = page.content.concerns[selectedIndex] || page.content.concerns[0];
  return <div className="space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-white p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#B59410]">Phase 4 · Full-page workflow</p><h1 className="font-serif text-2xl font-bold text-[#0B1B3D]">Sister Concerns Catalogue Editor</h1><p className="text-xs text-slate-500">Version {page.versionNumber} · {page.status} · {dirty ? 'Unsaved changes' : 'Up to date'} · {page.content.concerns.length} concerns</p></div><div className="flex flex-wrap gap-2"><Link href={`/admin-preview/concerns-page?slug=${encodeURIComponent(selected.slug)}`} target="_blank" className="rounded-xl border px-4 py-2 text-xs font-bold">Saved Preview</Link><button type="button" onClick={save} disabled={!dirty || busy} className="rounded-xl bg-slate-700 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{busy === 'save' ? 'Saving…' : 'Save Draft'}</button><button type="button" onClick={publish} disabled={dirty || busy || page.status !== 'draft'} className="rounded-xl bg-[#0B1B3D] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{busy === 'publish' ? 'Publishing…' : 'Publish'}</button></div></header>
    {message && <div className={`rounded-xl border p-3 text-xs font-semibold ${tone === 'error' ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}>{message}</div>}
    <nav className="flex flex-wrap gap-2">{TABS.map((name) => <button type="button" key={name} onClick={() => { setTab(name); if (name === 'Advanced') setAdvanced(JSON.stringify(payload(page), null, 2)); }} className={`rounded-xl px-4 py-2 text-xs font-bold ${tab === name ? 'bg-[#0B1B3D] text-white' : 'border bg-white text-slate-600'}`}>{name}</button>)}</nav>
    <section className="rounded-2xl border bg-white p-5">
      {tab === 'Shared Content' && <div className="space-y-6"><div><h2 className="mb-3 font-serif text-lg font-bold">Shared header media</h2><div className="grid gap-3 md:grid-cols-2">{page.content.header.media?.secureUrl && <img src={page.content.header.media.secureUrl} alt="" className="h-36 w-full rounded-xl object-cover" />}<div><Field label="Header image alt" value={page.content.header.imageAlt} onChange={(value) => update({ content: { ...page.content, header: { ...page.content.header, imageAlt: value } } })} /><p className="mt-2 text-[10px] text-slate-500">The current public header image remains fixed in this phase; concern overview media is selectable below.</p></div></div></div><div><h2 className="mb-3 font-serif text-lg font-bold">Shared detail-page labels</h2><div className="grid gap-3 md:grid-cols-3">{SHARED_FIELDS.map(([key, label]) => <Field key={key} label={label} value={page.content.labels[key]} onChange={(value) => updateShared(key, value)} multiline={key === 'notFoundBody'} />)}</div></div><label className="block rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-900"><input type="checkbox" checked={page.isVisible} onChange={(event) => update({ isVisible: event.target.checked })} /> Enable published Concern detail content</label></div>}
      {tab === 'Concerns' && <div>{selectedIndex === null ? <div><div className="mb-4 flex items-center justify-between"><div><h2 className="font-serif text-lg font-bold">Canonical sister concerns</h2><p className="text-xs text-slate-500">Edits remain draft-only until the full catalogue is published.</p></div><button type="button" onClick={addConcern} className="rounded-xl bg-[#0B1B3D] px-4 py-2 text-xs font-bold text-white">+ Add concern</button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{page.content.concerns.map((concern, index) => <article key={concern.concernId} className="rounded-xl border p-3">{concern.coverMedia?.secureUrl && <img src={concern.coverMedia.secureUrl} alt="" className="h-28 w-full rounded-lg object-cover" />}<div className="mt-3 flex justify-between gap-2"><div><span className="text-[9px] font-bold uppercase text-[#B59410]">{concern.isVisible === false ? 'hidden' : 'published'}</span><h3 className="font-serif text-sm font-bold text-[#0B1B3D]">{concern.name}</h3></div><div className="flex gap-1"><button type="button" onClick={() => setConcerns(move(page.content.concerns, index, -1))} disabled={!index} className="h-8 w-8 rounded-lg border disabled:opacity-30">↑</button><button type="button" onClick={() => setConcerns(move(page.content.concerns, index, 1))} disabled={index === page.content.concerns.length - 1} className="h-8 w-8 rounded-lg border disabled:opacity-30">↓</button></div></div><div className="mt-3 flex gap-2"><button type="button" onClick={() => setSelectedIndex(index)} className="flex-1 rounded-lg bg-slate-700 px-3 py-2 text-xs font-bold text-white">Edit details</button><button type="button" onClick={() => { if (page.content.concerns.length > 1 && confirm('Remove this concern from the next published catalogue?')) setConcerns(orders(page.content.concerns.filter((_, itemIndex) => itemIndex !== index))); }} className="rounded-lg border border-red-200 px-3 text-xs font-bold text-red-600">Remove</button></div></article>)}</div></div> : <div><div className="mb-4 flex items-center justify-between border-b pb-3"><div><button type="button" onClick={() => setSelectedIndex(null)} className="text-xs font-bold text-[#B59410]">← Back to catalogue</button><h2 className="mt-1 font-serif text-lg font-bold">Edit {selected.name}</h2></div><span className="font-mono text-[10px] text-slate-400">{selected.concernId}</span></div><ConcernForm concern={selected} availableProjects={page.availableProjects} onChange={(concern) => updateConcern(selectedIndex, concern)} onChooseCover={() => setPicker({ index: selectedIndex })} /></div>}</div>}
      {tab === 'Preview' && <div><div className="mb-4 flex items-center gap-3"><label className="text-xs font-bold">Preview concern</label><select value={selectedIndex ?? 0} onChange={(event) => setSelectedIndex(Number(event.target.value))} className={INPUT}>{page.content.concerns.map((concern, index) => <option value={index} key={concern.concernId}>{concern.name}</option>)}</select></div><div className="max-h-[760px] overflow-auto rounded-xl border"><ConcernDetailClient key={selected.concernId} concern={selected} concernsPage={page} previewMode /></div></div>}
      {tab === 'Advanced' && <div><p className="mb-3 text-xs text-slate-500">Complete structured Concerns payload. Database validation and media ID checks still apply.</p><textarea value={advanced} onChange={(event) => setAdvanced(event.target.value)} rows={34} spellCheck={false} className={`${INPUT} font-mono leading-5`} /><button type="button" onClick={applyAdvanced} className="mt-3 rounded-lg bg-slate-700 px-4 py-2 text-xs font-bold text-white">Apply structured content</button></div>}
    </section>
    {page.history?.length > 0 && <section className="rounded-2xl border bg-white p-5"><h2 className="font-serif text-lg font-bold">Revision history</h2>{page.history.map((item) => <div key={item.id} className="mt-2 flex justify-between rounded-lg bg-slate-50 p-3 text-xs"><span>{item.change_summary || 'Saved Concerns revision'}</span><span>v{item.version_number} · {new Date(item.created_at).toLocaleString()}</span></div>)}</section>}
    {picker && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-4"><div className="w-full max-w-7xl"><MediaLibrary isModal resourceTypeFilter="image" onSelectAsset={chooseMedia} onCloseModal={() => setPicker(null)} /></div></div>}
  </div>;
}
